# Generated by Django 5.2.3 on 2025-06-15 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=30, unique=True)),
                ('Artist', models.CharField(max_length=30)),
                ('Genre', models.CharField(choices=[('Pop Music', 'Pop Music'), ('Rock Music', 'Rock Music'), ('Jazz Music', 'Jazz Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Country Music', 'Country Music'), ('R&B Music', 'R&B Music'), ('Dance Music', 'Dance Music'), ('Other', 'Other')], max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image_URL', models.URLField()),
                ('Price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Owner', models.ManyToManyField(related_name='albums', to='profiles.profile')),
            ],
        ),
    ]
