# Generated by Django 5.2.3 on 2025-06-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Owner',
        ),
        migrations.AddField(
            model_name='album',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
