# Generated by Django 5.2.3 on 2025-06-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_owner_album_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Album_Name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Image_URL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Price',
            new_name='price',
        ),
    ]
