# Generated by Django 5.1.6 on 2025-02-17 14:20

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles', validators=[Petstagram.photos.validators.FileSizeValidator(file_size_mb=5, message='Photo size too big.Must be less than 5Mb.')]),
        ),
    ]
