# Generated by Django 5.1.6 on 2025-03-04 08:36

import DJ_Templates_Basics.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[DJ_Templates_Basics.posts.validators.BadLanguageValidator()]),
        ),
    ]
