# Generated by Django 5.2.3 on 2025-06-19 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Your name must contain letters only!')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Your name must contain letters only!')])),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Your passcode must be exactly 6 digits!')])),
                ('pets_number', models.PositiveIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
