# Generated by Django 5.2.3 on 2025-06-18 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
